sudo: false

language: node_js
node_js: "5.1"

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install
  - export PATH="`pwd`/node_modules/.bin:$PATH"
  - elm-package install --yes
  - (cd demo; elm-package install --yes)

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run make
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test
  # Test in several timezones (positive, negative, zero offset; DST; partial-hour offsets)
  - TZ=Etc/UTC $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # +0000/+0000
  - TZ=Pacific/Samoa $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # -1100/-1100
  - TZ=America/Chicago $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # -0600/-0500
  - TZ=Europe/Oslo $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # +0100/+0200
  - TZ=Asia/Tehran $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # +0330/+0430
  - TZ=Autralia/Eucla $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # +0845/+0845
  - TZ=Antarctica/South_Pole $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm test # +1200/+1300
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run css
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run make-demos

cache:
  directories:
    - sysconfcpus
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts
    - demo/elm-stuff/build-artifacts
